### Create new User
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdf@asdf.com",
  "password": "test123"
}


### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
"email": "asdf@asdf.com",
"password": "test123"
}

### Find by id
GET http://localhost:3000/auth/1


### Find all users by email
GET http://localhost:3000/auth?email=test2@gmail.com


### Delete user by id
DELETE http://localhost:3000/auth/5


### Update user
PATCH http://localhost:3000/auth/5
content-type: application/json

{
  "password": "asdsadsa"
}


### Who am i
GET http://localhost:3000/auth/whoami


### Sign out
POST http://localhost:3000/auth/signout